setup husky v2

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,70 +5,28 @@ set -e
 
 echo '🏗️👷 Styling, testing and building your project before committing'
 
-# Check Prettier standards
-yarn check-format ||
-(
-  echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
-      Prettier Check Failed. Run npm run format, add changes and try commit again.';
-  false;
+# Check Prettier
+yarn check-format || (
+  echo '🤢🤮 Prettier Check Failed. Run npm run format. 🤢🤮'
+  exit 1
 )
 
-# Check ESLint Standards
-yarn check-lint ||
-(
-        echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤
-                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
-        false; 
+# Check ESLint
+yarn check-lint || (
+  echo '😤🏀 ESLint Check Failed. Fix the weak shit! 😤🏀'
+  exit 1
 )
 
-# Check tsconfig standards
-yarn check-types ||
-(
-  echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
-      Are you seriously trying to write that? Make the changes required above.'
-  false;
+# Check Types
+yarn check-types || (
+  echo '🤡😂 Failed Type check. 🤡😂'
+  exit 1
 )
 
-# build
-yarn build ||
-(
-  echo '🤡🤡🤡🤡🤡 Failed to build. 🤡🤡🤡🤡🤡
-      Are you seriously trying to write that? Make the changes required above.'
-  false;
+# Build
+yarn build || (
+  echo '🤡🤡 Failed to build. 🤡🤡'
+  exit 1
 )
 
-# If everything passes... Now we can commit
-echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'# Check Prettier standards
-yarn check-format ||
-(
-  echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
-      Prettier Check Failed. Run npm run format, add changes and try commit again.';
-  false;
-)
-
-# Check ESLint Standards
-yarn check-lint ||
-(
-        echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤
-                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
-        false; 
-)
-
-# Check tsconfig standards
-yarn check-types ||
-(
-  echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
-      Are you seriously trying to write that? Make the changes required above.'
-  false;
-)
-
-# build
-yarn build ||
-(
-  echo '🤡🤡🤡🤡🤡 Failed to build. 🤡🤡🤡🤡🤡
-      Are you seriously trying to write that? Make the changes required above.'
-  false;
-)
-
-# If everything passes... Now we can commit
 echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
